### ISSUE TITLE
[FEATURE] Linting for docs

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10728]
I'd like to add some basic automatic checking of narrative documentation to the CI by adding the Vale GitHub action https://github.com/errata-ai/vale-action. I have been using this system locally for a few months and have configured it to work with all the .rst files I have been editing and creating for Bokeh. With the configuration I have created, the linter would be a helpful tool to support consistency according to the style guidelines in the documentation section of the developers guide.

I created this issue to work on how to best integrate this with Bokeh's CI. CC @bryevdv

**Comment by bryevdv** [comment]
(removed `status` -- only applies to PRs)

@tcmetzger looking at that action I think you can just add the Vale block there to one of the jobs in 

https://github.com/bokeh/bokeh/blob/branch-2.3/.github/workflows/bokehjs-ci.yml

Could be either Docs or Codebase. FWIW the docs job currently takes ~15 min and the codebase ~9 min so strictly from an "even out the CI job througput" perspective, the codebase job might be better.

**Comment by tcmetzger** [comment]
I'd try adding these steps to `.github/workflows/bokeh-ci.yml` in the section `codebase`:
```

    - name: Checkout
      uses: actions/checkout@master

    - name: Get Changed Files
      id: get_changed_files
      # include this action to filter for changed files only
      # (instead of checking entire docs every time)
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        # include remotely maintained "Google" style
        styles: |
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip

        # # only check modified lines, instead of all docs every time (feature currently broken)
        # onlyAnnotateModifiedLines: true
        # path to run Vale on
        files: '${{ steps.get_changed_files.outputs.all }}'
      env:
        # required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```
