### ISSUE TITLE
[FEATURE] - Option to disable the Bokeh logo in the toolbar via theme yaml file.

### ISSUE THREAD

**Issue by MatusGasparik** [bokeh/bokeh#12149]
### Problem description

Currently it is possible to remove the logo from the figure toolbar via `p.toolbar.logo = None`. One has to do it for every single figure and there is not option to do this globally.

### Feature description

Add the option to disable the logo via the theme yaml config, such as:

```yaml
attrs:
    Figure:
        toolbar_logo: null
```

### Potential alternatives

Doesn't apply.
