### ISSUE TITLE
[BUG] Nested gridplot collapses figures

### ISSUE THREAD

**Issue by Hoxbro** [bokeh/bokeh#12583]
### Software versions

``` yaml
Python version      :  3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /home/shh/miniconda3/envs/bokeh_clean/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.0.2-76060002-generic-x86_64-with-glibc2.35
```

### Expected behavior

I would expect that figures in the `GridPlot` do not collapse like when using `Row`.

### Observed behavior

The figure collapses in `GridPlot`. 

### Example code

```Python
from bokeh.io import output_notebook, show
from bokeh.layouts import Column, Row, gridplot
from bokeh.plotting import figure

output_notebook()


def fig():
    fig = figure(height=200, width=200)
    a = fig.line(x=list(range(10)), y=list(range(10)))
    return fig


def gp(func):
    plots = [[func(), func()]]
    return gridplot(plots)


def row(func):
    plots = [func(), func()]
    return Row(*plots)


nested_gridplot = Column(Column(gp(fig), row(fig)))
show(nested_gridplot)
```

### Screenshots

![image](https://user-images.githubusercontent.com/19758978/200818082-a1fd4599-952b-42ee-96cb-eca61a54682a.png)
