### ISSUE TITLE
[BUG] DataTable does not output true/false for numpy arrays

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#12776]
### Software versions

``` yaml
Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
IPython version     :  8.8.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev1
BokehJS static path :  /home/shh/miniconda3/envs/bkdev/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.12.1
npm version         :  8.19.2
Operating system    :  Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35
```

### Expected behavior

I would expect the numpy array to show up as true/false like the list. This is how it worked in Bokeh 2.

### Observed behavior

Numpy array outputs ones and zeros.

### Example code

```Python
import numpy as np
from bokeh.io import show
from bokeh.models import ColumnDataSource, DataTable, TableColumn

data = dict(list=[True] * 10, numpy=np.array([True] * 10))
source = ColumnDataSource(data)
columns = [TableColumn(field=c, title=c) for c in data]
data_table = DataTable(source=source, columns=columns)
show(data_table)
```

### Screenshots

**Bokeh 3**

![image](https://user-images.githubusercontent.com/19758978/216290867-889fa8e5-5073-4787-b971-b3dc51329f96.png)

**Bokeh 2**

![image](https://user-images.githubusercontent.com/19758978/216290638-e69c794e-4107-4fe7-8c05-260569f07109.png)
