### ISSUE TITLE
[BUG] DatetimePicker improvements

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#12904]
### Software versions

``` yaml
Python version      :  3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
IPython version     :  8.11.0
Tornado version     :  6.1
Bokeh version       :  3.1.0.dev5
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.13.0
npm version         :  8.19.3
Operating system    :  Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35

```

### Expected behavior

1) I would expect it to be a datetime (or a date).
2) The `min_date`/`max_date` ignore the timezone. 

### Observed behavior

Two problems I have observed: 

1) The value is a float. 
2) The `min_date`/`max_date` does not match the input, which probably is a timezone issue. 

### Example code

```Python
from datetime import date

from bokeh.io import curdoc
from bokeh.models import DatetimePicker

datetime_picker = DatetimePicker(
    title="Select date",
    value=date(2019, 10, 1),
    min_date=date(2019, 10, 1),  # Set to 2019-10-01 - 02:00 in the widget
    max_date=date(2019, 10, 30),  # Set to 2019-10-30 - 01:00 in the widget
)

print(datetime_picker.value)  # This is returning a float, would expect datetime (or date)

curdoc().add_root(datetime_picker)
```
