### ISSUE TITLE
[BUG] Patch does not output under certain conditions

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#12994]
### Software versions

``` yaml
Python version      :  3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
IPython version     :  8.11.0
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Linux-6.2.0-76060200-generic-x86_64-with-glibc2.35
```

### Browser name and version

Google chrome

### Jupyter notebook / Jupyter Lab version

3.6.1

### Expected behavior

Always show the patch plot

### Observed behavior

The patch plot is only shown under certain conditions.

This seems also to have been a problem before 3.0.

### Example code

```Python
import numpy as np
from bokeh.io import curdoc, output_notebook, show
from bokeh.models import ColumnDataSource, Patch
from bokeh.plotting import figure

output_notebook()

n = 400  # Works with 500, but will not work with 400

x_half = np.arange(start=4.0, stop=1100.1, step=0.1524)[n:]
x = np.concatenate([x_half, x_half[::-1]])
source = ColumnDataSource(dict(x=x, y=np.zeros_like(x)))

plot = figure()
glyph = Patch(x="x", y="y", fill_color="#f46d43")
plot.add_glyph(source, glyph)

show(plot)
```

### Stack traceback or browser console output

``` console
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at sort (<anonymous>:23778:24)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
    at sort (<anonymous>:23795:15)
```

### Screenshots

![image](https://user-images.githubusercontent.com/19758978/226301420-8fb3b1ae-1777-4182-89a4-5981ced91400.png)

![image](https://user-images.githubusercontent.com/19758978/226301478-733083ee-7623-4f38-89eb-99100aef49b8.png)
