### ISSUE TITLE
[BUG] Spinner in float mode with int step will increment to int

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13064]
### Software versions

``` yaml
Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Expected behavior

I expect the Spinner to increment with `value + 1` when the spinners mode is float and the step is an int. 

### Observed behavior

The increment is done to the (I think) `int(value + 1)`.

### Example code

```Python
from bokeh.io import output_notebook, show
from bokeh.layouts import column
from bokeh.models import Spinner

output_notebook()

a = Spinner(value=0.3, low=0, mode="float", step=1.0000000001, format="0.0")
b = Spinner(value=0.3, low=0, mode="float", step=1, format="0.0")
show(column(a, b))
```

### Screenshots

https://user-images.githubusercontent.com/19758978/230146082-032c9d2c-324d-42d6-b9f9-415752df7c0c.mp4
