### ISSUE TITLE
[BUG] Point draw does not work if color is an numpy array

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13155]
### Software versions

``` yaml
Python version      :  3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
IPython version     :  8.13.2
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Expected behavior

I would expect it to work the same regardless if it is a numpy array or a list. 

### Observed behavior

When using this example: https://docs.bokeh.org/en/3.1.1/docs/examples/interaction/tools/point_draw.html

and converting the color to a numpy array: 
``` python
source = ColumnDataSource({
    'x': [1, 5, 9], 'y': [1, 5, 9], 'color': np.array(['red', 'green', 'yellow'])
})
```
the example stops working and gives the console warning: `[bokeh] data source has columns of inconsistent lengths`

### Example code

```Python
Code here: https://docs.bokeh.org/en/3.1.1/docs/examples/interaction/tools/point_draw.html

And change the color to a numpy array.
```
