### ISSUE TITLE
[BUG] Gridplot with one figure having a title and another `frame_height` removes xlabel

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13225]
### Software versions

``` yaml
Python version      :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.0.dev4+15.g582a182d.dirty
BokehJS static path :  /home/shh/Repos/bokeh/src/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.7.1
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Expected behavior

No xlabel should disappear. 

### Observed behavior

Using a `gridplot` where one has a `title` set and the other one has a `frame_height` set. It will remove the second figures xlabel.  

First reported here: https://github.com/holoviz/holoviews/issues/5771

### Example code

```Python
from bokeh.plotting import figure, gridplot, show

p1 = figure(title="title", x_axis_label="x", y_axis_label="y")
p1.line(x=[0, 1], y=[0, 1])

p2 = figure(x_axis_label="x", y_axis_label="y", frame_height=200)
p2.line(x=[0, 1], y=[0, 1])

show(gridplot(children=[[p1, p2]]))
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/19758978/c375ab4b-2805-44c7-8ee3-a1f5e50e16b9)
