### ISSUE TITLE
[BUG] Enabling/Disabled DatePickers does not work

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13255]
### Software versions

``` yaml
Python version      :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.16.1
npm version         :  9.5.1
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Expected behavior

Expecting DatePicker and its family of models to be disabled like the TextInput.

First seen here https://github.com/holoviz/panel/issues/5254.

### Observed behavior

It does not disable it

### Example code

```Python
from bokeh.io import curdoc
from bokeh.models import Button, DatePicker, TextInput

date = DatePicker(title="DatePicker", value="2019-09-20")
text = TextInput(title="TextInput", value="2019-09-20")

# Bokeh button which disables the picker from python
button = Button(label="enable/disable")
button.on_click(lambda: setattr(date, "disabled", not date.disabled))
button.on_click(lambda: setattr(text, "disabled", not text.disabled))

curdoc().add_root(date)
curdoc().add_root(text)
curdoc().add_root(button)
```

### Screenshots

https://github.com/bokeh/bokeh/assets/19758978/31fcd03e-fab3-4488-94f5-880cfa26d108
