### ISSUE TITLE
[BUG] HoverTools not correctly located in Notebook 

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13428]
### Software versions

``` yaml
Python version      :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version     :  8.16.1
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /home/shh/miniconda3/envs/bokeh33/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.5.4-76060504-generic-x86_64-with-glibc2.35
```

### Jupyter notebook / Jupyter Lab version

4.0.6

### Expected behavior

The hovertool showing up around the mouse.

### Observed behavior

It does not see screenshot. 

### Example code

```Python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'b', 'C', 'd', 'E'],
))

TOOLTIPS = [
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
]

p = figure(width=400, height=400, tooltips=TOOLTIPS,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
```

### Screenshots

![ Screenshot 2023-10-11 12 45 48](https://github.com/bokeh/bokeh/assets/19758978/6c8d1d5b-fc63-4cd9-a119-ea1d8cf7351e)
