### ISSUE TITLE
[BUG] daylight_warsaw_2013 emits a warning

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13435]
### Software versions

``` yaml
Python version      :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version     :  8.16.1
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v20.8.0
npm version         :  10.1.0
Operating system    :  Linux-6.5.4-76060504-generic-x86_64-with-glibc2.35
```

And pandas version 2.1.1

### Expected behavior

No warning

### Observed behavior

`from bokeh.sampledata.daylight import daylight_warsaw_2013` emit a warning:

``` python-traceback
/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/util/sampledata.py:145: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
```

### Example code

```Python
from bokeh.sampledata.daylight import daylight_warsaw_2013
```
