### ISSUE TITLE
[BUG] BoxAnnotation don't show up if not all lrbt-bounds are set

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13432]
### Software versions

``` yaml
Python version      :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version     :  8.16.1
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v20.8.0
npm version         :  10.1.0
Operating system    :  Linux-6.5.4-76060504-generic-x86_64-with-glibc2.35
```

### Expected behavior

It seems like BoxAnnotation is broken in 3.3:

This is how it looked in Bokeh 3.2:
https://docs.bokeh.org/en/3.2.2/docs/examples/basic/annotations/box_annotation.html

Setting all values to None makes them reappear. In 3.3, they are set to `np.nan`. 

``` python
low_box = BoxAnnotation(top=80, bottom=None, left=None, right=None, fill_alpha=0.2, fill_color='#D55E00')
mid_box = BoxAnnotation(bottom=80, top=180, left=None, right=None, fill_alpha=0.2, fill_color='#0072B2')
high_box = BoxAnnotation(bottom=180, top=None, left=None, right=None, fill_alpha=0.2, fill_color='#D55E00')
```

### Observed behavior

And this is how it looks in 3.3:

https://docs.bokeh.org/en/3.3.0/docs/examples/basic/annotations/box_annotation.html

### Example code

```Python
See URLs above.
```
