### ISSUE TITLE
[BUG] Latex does not render in Notebook

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13499]
### Software versions

``` yaml
Python version      :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version     :  8.17.2
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v20.8.1
npm version         :  10.1.0
Operating system    :  Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
```

### Jupyter notebook / Jupyter Lab version

jupyter lab: 3.6.6

### Expected behavior

LaTeX to be rendered in a notebook

### Observed behavior

LaTeX is not rendered, I suspect it is related to https://github.com/bokeh/bokeh/pull/13214

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.models import Label

output_notebook()

x = np.arange(-2*np.pi, 2*np.pi, 0.1)
y = np.sin(x)

p = figure(height=250, title=r"$$\sin(x)$$ for $$x -2\pi$$ and $$2\pi$$")
p.scatter(x, y, alpha=0.6, size=7)

label = Label(
    text=r"$$y = \sin(x)$$",
    x=150, y=130,
    x_units="screen", y_units="screen",
)
p.add_layout(label)

p.yaxis.axis_label = r"$$\sin(x)$$"
p.xaxis.axis_label = r"\(x\pi\)"

show(p)
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/19758978/50ae5b5c-26a5-4bda-954f-a002c6c5c03e)
