### ISSUE TITLE
[BUG] EqHistColorMapper has become significant slower in Bokeh 3.3

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13542]
### Software versions

``` yaml
Python version        :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.3.1
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v20.8.1
npm version           :  10.1.0
jupyter_bokeh version :  3.0.7
Operating system      :  Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
```

### Expected behavior

Same speed as in Bokeh 3.2

### Observed behavior

Using `EqHistColorMapper` as a `color_mapper` has become significantly slower in showing up in Bokeh 3.3. Not a problem when using Bokeh 3.2.2

### Example code

```Python
import numpy as np
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.transform import EqHistColorMapper

p = figure(match_aspect=True)
color_mapper = EqHistColorMapper(palette=["blue", "red"])
image = np.diag(np.ones(400))
p.image(x=[-0.5], y=[-0.5], dw=[1], dh=[1], image=[image], color_mapper=color_mapper)
curdoc().add_root(p)
```

### Bokeh 3.2.2

https://github.com/bokeh/bokeh/assets/19758978/6fd7a5fd-0070-482f-9f43-4ebe2abcde7d

### Bokeh 3.3.1 

https://github.com/bokeh/bokeh/assets/19758978/e6492249-675f-49eb-842b-7d9afcba07af
