### ISSUE TITLE
[BUG] Improve NaT support for HoverTool

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13598]
### Software versions

``` yaml
Python version        :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version       :  8.18.1
Tornado version       :  6.3.3
Bokeh version         :  3.3.2
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v20.9.0
npm version           :  10.1.0
jupyter_bokeh version :  3.0.7
Operating system      :  Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
```

### Expected behavior

I'm unsure if this is a feature request or a bug report. 

I have the example code below, and when I hover over a NaT date, I get `NaN-NaN-NaN` as the value, I think it would be cleaner to have it output a single output like `NaT`.

Unrelated: I noticed that a nan value in an array with a datetime formatted will output `function () { return request.convert(arguments);}`, which could be a bug. 

### Observed behavior

I get `NaN-NaN-NaN` when I hover over a NaT value.

### Example code

```Python
import numpy as np

from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure, show


source = ColumnDataSource(
    data=dict(
        x=[0],
        y=[0],
        date=np.array([np.datetime64("2020-01-01")]),
        nat_date=np.array([np.datetime64("NAT")]),
        nan_date=np.array([np.nan]),
    )
)

TOOLTIPS = [
    ("date", "@date{%F}"),
    ("nat_date", "@nat_date{%F}"),
    ("nan_date", "@nan_date{%F}"),
]

hovertool = HoverTool(
    tooltips=TOOLTIPS,
    formatters={"@date": "datetime", "@nat_date": "datetime", "@nan_date": "datetime"},
)

p = figure(width=400, height=400)
p.add_tools(hovertool)
p.circle("x", "y", size=20, source=source)

show(p)
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/19758978/19ea85d8-8fa5-4323-adfb-8782b5d4582e)
