### ISSUE TITLE
[BUG] `autosize_mode` does not work when data is string

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13658]
### Software versions

``` yaml
Python version        :  3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
IPython version       :  8.20.0
Tornado version       :  6.3.3
Bokeh version         :  3.3.3
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v20.9.0
npm version           :  10.1.0
jupyter_bokeh version :  3.0.7
Operating system      :  Linux-6.6.6-76060606-generic-x86_64-with-glibc2.35
```

### Expected behavior

The table should show up.

### Observed behavior

 `autosize_mode` does not work when data is string (maybe more) as it does not show up.

### Example code

```Python
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, DataTable, TableColumn

output_notebook()

data = dict(
    data=["A", "B", "C"],
    # data = [1, 2, 3],  # works
)
source = ColumnDataSource(data)

columns = [
    TableColumn(field="data"),
]
data_table = DataTable(source=source, columns=columns, autosize_mode="fit_columns")

show(data_table)
```

### Stack traceback or browser console output

``` console
Uncaught (in promise) ReferenceError: row is not defined
    getColContentSize https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.js:13414
    getColAutosizeWidth https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.js:13324
    autosizeColumns https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.js:13174
    updateLayout https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.js:1104
    _after_render https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.js:1283
    after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.js:44247
    r_after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.js:44244
    render_to https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.js:44233
    render_view https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.js:8035
bokeh-tables-3.3.3.js:13414:21
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/19758978/055f6ced-ca16-402a-9bc2-ad8be754a5e1)
