### ISSUE TITLE
[BUG] Enforce `max_interval` / `min_interval` if `{x,y}_range` is not set 

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13725]
### Software versions

``` yaml
Python version        :  3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
IPython version       :  8.22.1
Tornado version       :  6.4
Bokeh version         :  3.4.0.dev8
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v20.9.0
npm version           :  10.1.0
jupyter_bokeh version :  4.0.0
Operating system      :  Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
```

### Expected behavior

`max_interval` and `min_interval` was added in https://github.com/bokeh/bokeh/pull/13561. If no `{x,y}_range` is set, it should not exceed `max_interval`. 

I'm not sure if this is a bug report or a feature request.

### Observed behavior

The initial render has the full range of the plots, and when you move it, it snaps to the `max_interval` size. 

### Example code

```Python
import numpy as np
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show


n_points = 3000
x_values = np.linspace(0, 100, n_points)
y_values = np.random.randn(n_points).cumsum()

source = ColumnDataSource(data=dict(x=x_values, y=y_values))

p = figure(
    height=300,
    width=800,
    tools=[" xpan", "xzoom_in", "xzoom_out", "reset"],
    background_fill_color="#efefef",
    # x_range=(20, 30),
)
p.line("x", "y", source=source)
p.yaxis.axis_label = "Value"
p.x_range.max_interval = 10  # Set max zoom interval

select = figure(
    height=130,
    width=800,
    y_range=p.y_range,
    tools="",
    toolbar_location=None,
    background_fill_color="#efefef",
)
range_tool = RangeTool(x_range=p.x_range)
range_tool.overlay.fill_color = "navy"
range_tool.overlay.fill_alpha = 0.2
select.line("x", "y", source=source)
select.ygrid.grid_line_color = None
select.add_tools(range_tool)

show(column(p, select))
```

### Screenshots

https://github.com/bokeh/bokeh/assets/19758978/1716ac2e-7523-4f17-90fe-15b7bf0957db
