### ISSUE TITLE
UI gesture detection fails in interactive tests in FireFox

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13928]
### Software versions

``` yaml
Python version        :  3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
IPython version       :  8.24.0
Tornado version       :  6.4
Bokeh version         :  3.5.0.dev6+2.g33e3a508.dirty
BokehJS static path   :  /home/shh/projects/bokeh/src/bokeh/server/static
node.js version       :  v20.12.2
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
```

### Browser name and version

Mozilla Firefox 125.0.3

### Expected behavior

No console errors

### Observed behavior

When reviewing https://github.com/bokeh/bokeh/pull/13918, I noticed that when running http://127.0.0.1:5777/unit/run?k=13831, I would get the following console error:

 

### Example code

```Python
http://127.0.0.1:5777/unit/run?k=13831
```

### Stack traceback or browser console output

``` console
[bokeh 3.5.0-dev.5] Bokeh does not support Polygons with holes in, only exterior ring used. geojson_data_source.js:68
[bokeh 3.5.0-dev.5] MultiPoint not supported in Bokeh geojson_data_source.js:80
[bokeh 3.5.0-dev.5] Bokeh does not support Polygons with holes in, only exterior ring used. geojson_data_source.js:97
GET
http://127.0.0.1:5777/favicon.ico
[HTTP/1.1 404 Not Found 1ms]

[bokeh 3.5.0-dev.5] document idle at 25 ms document.js:91
Uncaught DOMException: Element.setPointerCapture: Invalid pointer id
    _pointer_down ui_gestures.js:119
    emit interactive.js:124
    tap interactive.js:106
    tap_at regressions.js:1287
    _ regressions.js:1290
    _run_test framework.js:235
    yield_all framework.js:135
    run_all framework.js:106
    <anonymous> run:76
    async* run:77
ui_gestures.js:119
Uncaught Error: unreachable code
    UnreachableError assert.js:7
    unreachable assert.js:26
    _pointer_up ui_gestures.js:229
    emit interactive.js:124
    tap interactive.js:106
    tap_at regressions.js:1287
    _ regressions.js:1290
    _run_test framework.js:235
    yield_all framework.js:135
    run_all framework.js:106
    <anonymous> run:76
    async* run:77
assert.js:7
Error: expected [] to be equal to [0]
    ExpectationError assertions.js:185
    equal assertions.js:82
    _ regressions.js:1291
    _run_test framework.js:235
    yield_all framework.js:135
    run_all framework.js:106
    <anonymous> run:76
    async* run:77
framework.js:108
```

### Screenshots

![ Screenshot 2024-06-10 09 49 07](https://github.com/bokeh/bokeh/assets/19758978/a6430cf5-85de-420e-9bb2-7f33283533ab)
