### ISSUE TITLE
Bokeh 3.7 type hinting does not work for Python 3.10 and Python 3.11

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14351]
### Software versions

``` yaml
Python version        :  3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:17:24) [GCC 13.3.0]
IPython version       :  8.32.0
Tornado version       :  6.4.2
NumPy version         :  2.1.3
Bokeh version         :  3.7.0.dev8
BokehJS static path   :  /home/shh/projects/holoviz/repos/panel/.pixi/envs/test-type/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v22.12.0
npm version           :  10.9.0
jupyter_bokeh version :  4.0.5
Operating system      :  Linux-6.13.3-arch1-1-x86_64-with-glibc2.41
```

### Expected behavior

To avoid errors. And have type hinting be compatible with all Python versions supported by Bokeh. 

### Observed behavior

Trying out Panel with the latest dev release, I get the following error out
https://github.com/holoviz/panel/actions/runs/13453996608/job/37593965982?pr=7724

![Image](https://github.com/user-attachments/assets/ccf4e0ea-c702-443e-9dd7-1766cda360c9)

https://github.com/bokeh/bokeh/blob/89ada590e6f9de4706cb20ced9e750ca937dc872/src/bokeh/core/has_props.pyi#L36-L36

### Example code

```Python
-
```
