### ISSUE TITLE
`ValueRef` `formatter` does not handle datetime nullable well

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14413]
### Software versions

``` yaml

Python version        :  3.11.11 | packaged by conda-forge | (main, Mar  3 2025, 20:43:55) [GCC 13.3.0]
IPython version       :  9.0.2
Tornado version       :  6.4.2
NumPy version         :  2.2.3
Bokeh version         :  3.8.0.dev1+3.g3809c694
BokehJS static path   :  /home/shh/projects/bokeh/src/bokeh/server/static
node.js version       :  v20.18.1
npm version           :  10.8.2
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.13.5-arch1-1-x86_64-with-glibc2.41

```

### Expected behavior

I would want it to return something similar to what basic-formatter does

### Observed behavior

I have some datetime values with nullable values in it, which I want to format with the new `ValueRef` `format` introduced in Bokeh 3.7. This gives weird output for None or NaN:

![Image](https://github.com/user-attachments/assets/c4dc2d5d-abec-4e28-b969-0b3f29f9996b)
![Image](https://github.com/user-attachments/assets/bdbf9030-a158-4f04-a450-53548828fbce)

With datetime:

![Image](https://github.com/user-attachments/assets/561ff932-4440-416f-9fa0-7a73e539bd90)

### Example code

```Python
from datetime import datetime

import numpy as np
from bokeh.io import output_notebook, show
from bokeh.models import Select
from bokeh.models.dom import HTML, ValueOf

output_notebook()
select_any_value = Select(
    value=datetime(2025, 1, 1),
    options=[
        (datetime(2025, 1, 1), "datetime"),
        (None, "None"),
        (np.nan, "NaN"),
    ],
)
select_any_value.title = HTML(
    html=[
        "Selected value: <b>",
        ValueOf(obj=select_any_value, attr="value", formatter="datetime", format="%Y %B %d"),
        ", ",
        ValueOf(obj=select_any_value, attr="value", formatter="basic"),
        "</b>",
    ]
)

show(select_any_value)
```
