### ISSUE TITLE
Legend renderer not correctly positioned when saved with SaveTool

### ISSUE THREAD

**Issue by efbulle** [bokeh/bokeh#14422]
### Software versions

Python version        :  3.13.2 (tags/v3.13.2:4f8bb39, Feb  4 2025, 15:23:48) [MSC v.1942 64 bit (AMD64)]
IPython version       :  9.0.2
Tornado version       :  6.4.2
NumPy version         :  2.2.3
Bokeh version         :  3.7.0
BokehJS static path   :  C:\Users\emman\src\essais\.venv\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-11-10.0.26100-SP0

### Browser name and version

Chrome Version 134.0.6998.89 or Edge Version 134.0.3124.72 

### Expected behavior

In 3.6 legend renderers are as expected

![Image](https://github.com/user-attachments/assets/54baa775-7435-4ae2-80cb-c939f01165d2)

### Observed behavior

In 3.7.0, SaveTool doesn’t behave the same : Legend renderers are shifted outside of the legend box.

![Image](https://github.com/user-attachments/assets/eeb9b71a-606e-4b19-9fa6-d8dc01eb4657)

### Example code

```Python
from bokeh.plotting import figure, show

p = figure()
p.line([1, 2], [2, 1], line_width=4, legend_label="line")
show(p)
```

**Comment by mattpap** [comment]
@bokeh/dev, can someone reproduce this on Windows? I'm getting the correct behavior in all browsers on Linux. We also have tests for this particular behavior.

**Comment by mosc9575** [comment]
Edited!

I am able to reproduce this using Windows 10. I am getting the expected legend in a Jupyter Notebook in VSCode, in Chrome and Firefox. After saving with the saving tool, the the figure looks like below:

![Image](https://github.com/user-attachments/assets/57aac62b-2ec3-4a94-9480-94c882829da3)


<details><summary>technical information</summary>
Python version        :  3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
IPython version       :  8.25.0
Tornado version       :  6.4.1
NumPy version         :  1.26.4
Bokeh version         :  3.7.0
BokehJS static path   :  [C:\Users\mosc\Envs\fbpinn\Lib\site-packages\bokeh\server\static](file:///C:/Users/mosc/Envs/fbpinn/Lib/site-packages/bokeh/server/static)
node.js version       :  v20.17.0
npm version           :  10.8.2
jupyter_bokeh version :  4.0.5
Operating system      :  Windows-10-10.0.19045-SP0
</details>

~~I will try Windows 11 later, too.~~

**Comment by efbulle** [comment]
To be exact, I do get the expected legend in the notebook or in the html page, but not when I save the picture with the savetool or the new copy or open context menus.

**Comment by hoxbro** [comment]
I can recreate it on Linux if I zoom in and save it:


![Image](https://github.com/user-attachments/assets/8791a9f8-f790-4cea-b0c4-f21ffa5127b4)

``` yaml
❯ bokeh info
Python version        :  3.11.11 | packaged by conda-forge | (main, Mar  3 2025, 20:43:55) [GCC 13.3.0]
IPython version       :  9.0.2
Tornado version       :  6.4.2
NumPy version         :  2.2.3
Bokeh version         :  3.8.0.dev1+3.g3809c694
BokehJS static path   :  /home/shh/projects/bokeh/src/bokeh/server/static
node.js version       :  v20.18.1
npm version           :  10.8.2
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.13.6-arch1-1-x86_64-with-glibc2.41

❯ librewolf --version
Mozilla Firefox 136.0.1-1

```
