### ISSUE TITLE
Patches with no data does not show plot with Bokeh 3.7+

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14424]
### Software versions

``` yaml
Python version        :  3.11.11 | packaged by conda-forge | (main, Mar  3 2025, 20:43:55) [GCC 13.3.0]
IPython version       :  9.0.2
Tornado version       :  6.4.2
NumPy version         :  2.2.3
Bokeh version         :  3.8.0.dev1+3.g3809c694
BokehJS static path   :  /home/shh/projects/bokeh/src/bokeh/server/static
node.js version       :  v20.18.1
npm version           :  10.8.2
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.13.6-arch1-1-x86_64-with-glibc2.41
```

### Expected behavior

Have the same behavior as in Bokeh 3.6, where it shows an empty figure.

### Observed behavior

Running the example below does not show anything on Bokeh 3.7+

### Example code

```Python
from bokeh.io import show
from bokeh.models import ColumnDataSource, Patches
from bokeh.plotting import figure

source = ColumnDataSource()

plot = figure()
glyph = Patches(xs="xs", ys="ys")
plot.add_glyph(source, glyph)

show(plot)
```

### Stack traceback or browser console output

``` console
[bokeh 3.8.0-dev.1] setting log level to: 'info' bokeh.js:4568:28
[bokeh 3.8.0-dev.1] attempted to retrieve property array for nonexistent field 'xs' bokeh.js:4108:42
[bokeh 3.8.0-dev.1] expected a 2-d array for Patches.xs bokeh.js:27844:38
Uncaught (in promise) Error: expected a 2-d array for Patches.xs
    _transform_array glyph.js:334
    set_data glyph.js:385
    set_data glyph_renderer.js:189
    lazy_initialize glyph_renderer.js:101
    _build_view build_views.js:13
    build_views build_views.js:35
    _build_renderers plot_canvas.js:638
    build_renderer_views plot_canvas.js:664
    lazy_initialize plot_canvas.js:294
    _build_view build_views.js:13
    build_view build_views.js:17
    build_view view_manager.js:104
    render_view standalone.js:49
    render_model standalone.js:59
    add_document_standalone standalone.js:70
    _embed_items index.js:57
    embed_items index.js:42
    embed_document example.html:37
    fn example.html:40
    fn example.html:56
    safely safely.js:53
    fn example.html:32
    EventListener.handleEvent* example.html:60
    <anonymous> example.html:61
bokeh.js:27845:27
Error: ⛔ Core error code: InvalidTabOrUrl injected.js:6:25694
```

### Screenshots

On Bokeh 3.6:

![Image](https://github.com/user-attachments/assets/d76d3bfe-de5f-415d-bfc9-607e3e6d5d3f)
