### ISSUE TITLE
Improve handling of pd.NA in Property.matches

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14476]
### Software versions

``` yaml
Python version        :  3.13.3 | packaged by conda-forge | (main, Apr 14 2025, 20:44:03) [GCC 13.3.0]
IPython version       :  9.2.0
Tornado version       :  6.4.2
NumPy version         :  2.2.5
Bokeh version         :  3.7.2
BokehJS static path   :  /home/shh/.local/conda/envs/holoviz/lib/python3.13/site-packages/bokeh/server/static
node.js version       :  v22.13.0
npm version           :  10.9.2
jupyter_bokeh version :  4.0.5
Operating system      :  Linux-6.14.4-arch1-1-x86_64-with-glibc2.41
```

### Expected behavior

`pd.NA` is a weird object, and I have seen it cause problems in more complex code. I have attached some MRE.

I would like to apply the following diff.

``` diff
diff --git a/src/bokeh/core/property/bases.py b/src/bokeh/core/property/bases.py
index db43671f3b..b6763057f8 100644
--- a/src/bokeh/core/property/bases.py
+++ b/src/bokeh/core/property/bases.py
@@ -269,10 +269,10 @@ class Property(PropertyDescriptorFactory[T]):
             # FYI Numpy can erroneously raise a warning about elementwise
             # comparison here when a timedelta is compared to another scalar.
             # https://github.com/numpy/numpy/issues/10095
-            return new == old
+            return bool(new == old)
 
         # if the comparison fails for some reason, just punt and return no-match
-        except ValueError:
+        except (ValueError, TypeError):
             return False
 
     def transform(self, value: Any) -> T:
```

### Observed behavior

Can raise TypeError and return itself.

### Example code

```Python
import pandas as pd
from bokeh.core.property.bases import Property

Property().matches(pd.NA, pd.NA)  # Return pd.NA
Property().matches({"name": pd.NA}, {"name": 1})  # Raises TypeError
```

### Stack traceback or browser console output

``` python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 4
      1 import pandas as pd
      2 from bokeh.core.property.bases import Property
----> 4 Property().matches({"name": pd.NA}, {"name": 1})

File [~/.local/conda/envs/holoviz/lib/python3.13/site-packages/bokeh/core/property/bases.py:267](http://localhost:8888/home/shh/.local/conda/envs/holoviz/lib/python3.13/site-packages/bokeh/core/property/bases.py#line=266), in Property.matches(self, new, old)
    265     if set(new.keys()) != set(old.keys()):
    266         return False
--> 267     return all(self.matches(new[k], old[k]) for k in new)
    269 # FYI Numpy can erroneously raise a warning about elementwise
    270 # comparison here when a timedelta is compared to another scalar.
    271 # https://github.com/numpy/numpy/issues/10095
    272 return new == old

File missing.pyx:392, in pandas._libs.missing.NAType.__bool__()

TypeError: boolean value of NA is ambiguous
```
