### ISSUE TITLE
Only create CSS rules to bokeh classes to avoid styling external elements

### ISSUE THREAD

**Issue by leafty** [bokeh/bokeh#2589]
When including bokeh css in an html page to embed bokeh plots, it includes general styling rules. For example, we have:
```css
label {
  display: inline-block;
  margin-bottom: 5px;
  font-weight: bold;
}
```
Bokeh should not do this and should always apply rules to its own elements (like `.bk-canvas`).
