### ISSUE TITLE
HoverTool tooltip CSS is vunerable to being overridden by other page CSS

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5102]
Viewable at https://bokeh.github.io/blog/2016/9/6/release-0-12-2/ (the Texas example).

Source at: https://github.com/bokeh/bokeh.github.io/tree/source/content/blog/release-0-12-2

It appears that the lektor css is overridding some of the hover tooltip css so that the rendered tooltip has some extraneous horizontal lines and an extra row at the bottom:

<img width="662" alt="screen shot 2016-09-06 at 5 25 44 pm" src="https://cloud.githubusercontent.com/assets/2198981/18293209/08a78e90-7457-11e6-9b20-b66daaf90b00.png">

ping @birdsarah

**Comment by birdsarah** [comment]
The offending lines from skeleton.css are this:

```css
pre, blockquote, dl, figure, table, p, ul, ol, form {
    margin-bottom: 2.5rem;
}

th, td {
    border-bottom: 1px solid #E1E1E1;
}
```

We could fix up these properties, but this is just a silly game of whack-a-mole - which I already played once with the jupyter notebook CSS. The solution is to re-write the hover template to not use tables (which is what jupyter and this skeleton css is trying to style) and use custom-styled divs, which should seriously reduce, if not practically eliminate (due to bk-root namespace), the chances of this happening again.
