### ISSUE TITLE
Adverse effects of deprecating Glyph functions accepting literals and datasource

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#5449]
A recent deprecation warning for Glyph functions accepting literals and a datasource ( https://github.com/bokeh/bokeh/issues/2056 ) seems to be breaking a simple yet potentially common use case. In particular, it seems we cannot specify the `color` keyword argument via the `ColumnDataSource`. As a result, they cannot be combined into a single `ColumnDataSource`. So the colors need to be supplied as a separate `list`. However, this seems to result in running into this deprecation warning as can be seen with this [example]( https://github.com/jakirkham/bokeh_examples/blob/efc363b0ba282d8fa411e4451fb4a629809b878a/Bokeh_Example_16.ipynb ).

The test environment can be created using this `conda` environment file.

```yml
# test_env.yml

name: bkenv
channels:
- nanshe
- jakirkham
- conda-forge
- defaults
- javascript
dependencies:
- appnope=0.1.0=py27_0
- bokeh=0.12.3=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_0
- conda-forge::backports_abc=0.4=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2016.9.26=0
- conda-forge::certifi=2016.9.26=py27_0
- conda-forge::configparser=3.5.0=py27_0
- conda-forge::decorator=4.0.10=py27_0
- conda-forge::entrypoints=0.2.2=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::ipykernel=4.5.0=py27_0
- conda-forge::ipython=5.1.0=py27_1
- conda-forge::ipython_genutils=0.1.0=py27_0
- conda-forge::jinja2=2.8=py27_1
- conda-forge::jsonschema=2.5.1=py27_0
- conda-forge::jupyter_client=4.4.0=py27_0
- conda-forge::jupyter_core=4.2.0=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::markupsafe=0.23=py27_0
- conda-forge::mistune=0.7.3=py27_0
- conda-forge::nbconvert=4.2.0=py27_0
- conda-forge::nbformat=4.1.0=py27_0
- conda-forge::ncurses=5.9=9
- conda-forge::notebook=4.2.3=py27_0
- conda-forge::numpy=1.11.2=py27_blas_openblas_200
- conda-forge::openblas=0.2.18=6
- conda-forge::openssl=1.0.2h=2
- conda-forge::pathlib2=2.1.0=py27_0
- conda-forge::pexpect=4.2.0=py27_1
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.8=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.1.3=py27_1
- conda-forge::python=2.7.12=1
- conda-forge::python-dateutil=2.5.3=py27_0
- conda-forge::pyyaml=3.11=py27_0
- conda-forge::pyzmq=16.0.0=py27_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.11.1=py27_0
- conda-forge::setuptools=28.7.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_0
- conda-forge::terminado=0.6=py27_0
- conda-forge::tk=8.5.19=0
- conda-forge::tornado=4.4.2=py27_0
- conda-forge::traitlets=4.3.1=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zlib=1.2.8=3
- mkl=11.3.3=0
- python.app=1.2=py27_4
```
