### ISSUE TITLE
Have theme.yaml apply to a named model

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5908]
Currently theme.yaml only applies to Model classes.

There's lots of capability I'd like for theming, but a simple first step (already briefly discussed with @bryevdv) would be to be able to specify a model name in theme.yaml. For example:

```python
p = figure()
p.circle(x=[1, 2], y=[1, 2])
p.xaxis.name = 'xaxis'
p.yaxis.name = 'yaxis'
```

```yaml
models:
    Axis:
        axis_line_color: null
        major_label_text_color: null
        major_tick_line_color: null
        minor_tick_line_color: null
names:
    xaxis:
       major_label_text_color: pink
   yaxis:
       major_label_tect_color: blue
```

I'm not wed to the `models`, `names` idea above. Just a thought.

The net result is that:
* `xaxis` and `yaxis` would inherit all the properties from Axis
* `xaxis` would get pink color
* `yaxis` would get blue color

Note the requirement to be able to specify a property at Axis level and then override it in the names. This would be important in the case, for example, where you have 7 circles. You want them all to have some common base properties but you want to tweak one property in one case. You don't want to have to specify the default case for all others because you want to specialize one.
