### ISSUE TITLE
Bokeh CSS affects all HTML components in bokeh layout

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8788]
In the major layout refactor a crucial bit of CSS was added which ensures that bokeh takes control over all margins and padding, specifically I'm referring to this snippet in ``bokehjs/src/less/bokeh.less``:

```css
.bk-root {
  *, *:before, *:after {
    box-sizing: inherit;
    margin: 0;
    border: 0;
    padding: 0;
    background-image: none;
  }
}
```

 I realize this code is essential for a layout components to work, however problematically it also applies to the contents of any ``Div`` or other LayoutDOM object. For examples when declaring a ``Div`` with a list declared using ``<ul>`` tags in it, the padding definition from above causes the list to render incorrectly:

```python
from bokeh.models.widgets import Div

div = Div(text="""
<ul>
  <li>Test</li>
  <li>Test</li>
  <ul>
    <li>Sublist</li>
    <li>Sublist 2</li>
  </ul>
  <li>Test</li>
</ul>
""")
```

![Screen Shot 2019-03-25 at 5 03 14 PM](https://user-images.githubusercontent.com/1550771/54939216-ea009d00-4f1f-11e9-963c-b46c659267e2.png)

We can restore behavior by overriding the inline style of the ``ul`` tags with ``padding: 4px !important`` but that seems pretty hacky. Is there any way of changing the bokeh CSS to apply those padding/border/margin styles only to bokeh layouts and other dom components but not have them apply inside those DOM components?
