### ISSUE TITLE
[FEATURE] add broader themes

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#9339]
Currently we can define a theme to set specific attributes of specific models like below from the examples in https://docs.bokeh.org/en/latest/docs/reference/themes.html

```
attrs:
    Figure:
        background_fill_color: '#2F2F2F'
        border_fill_color: '#2F2F2F'
        outline_line_color: '#444444'
    Grid:
        grid_line_dash: [6, 4]
        grid_line_alpha: .3
    Title:
        text_color: "white"
```

Would it be possible to add something a bit more powerfull like matplotlib's rcParams to set attributes like text properties for all the text in the document. For example with matplotlib we can do `rcParams.update({'font.size':15})` and the font size of all text, from titles, to axis labels, to legend labels, is updated.

Alternatively I loop over all the models I know in the document that have text, look at their .properties_with_values() dictionary, and build the theme dictionary by looking for all the attributes that include e.g. "text_font_size".

**Comment by mattpap** [comment]
This would be nice feature. Will need to discuss details of how this would work. I suppose something like this as a starter:
```yaml
attrs:
    *:
        text_color: "white"
```
where `*` is a case of some query language, like glob, regex or maybe xpath-like if we would like to give true flexibility to the user.

**Comment by rocheseb** [comment]
Yes that would be great, especially if it worked with the current themes:
```
attrs:
    *:
        text_color: "white"
    Title:
        text_color: "blue"
```

All text would be white except for Title models which would be blue

**Comment by bryevdv** [comment]
Thinking about this also from the other issue wanting to target themes to named objects, I might suggest this instead:
```
# theme by mode type
attrs:
    Figure:
        background_fill_color: '#2F2F2F'

# theme by model name
names:
    foo: major_label_orientation: 0.4

# theme by property kind
props:
    text_font: "arial"
```
